#+TITLE: zshrc configuration file
#+PROPERTY: header-args :tangle ~/.zshrc

* Table of contents :toc:
- [[#environment-variables][Environment variables]]
- [[#setting-up-brew-environment][Setting up brew environment]]
- [[#setting-up-gem-home][Setting up gem home]]
- [[#setting-up-path-environment-variable][Setting up PATH environment variable]]
- [[#setting-up-installed-libraries][Setting up installed libraries]]
- [[#setting-other-paths][Setting other paths]]
- [[#setting-up-oh-my-zsh-environment-variables][Setting up oh-my-zsh environment variables]]
- [[#plugins][Plugins]]
- [[#sourcing-oh-my-zsh-after-all-obligated-staff][Sourcing oh-my-zsh after all obligated staff]]
- [[#preferred-viewer-and-editor][Preferred viewer and editor]]
- [[#aliases][Aliases]]

* Environment variables

- Setting up path to your oh-my-zsh installation.
- Setting up xterm colors.
- Setting up my language environment.
- Make CMake use colors

#+BEGIN_SRC sh
export ZSH="$HOME/.oh-my-zsh"
export LANG=en_US.UTF-8
if [[ "$(uname)" == "Linux" ]]; then
  export TERM=xterm-256color
fi
export CLICOLOR_FORCE=1
#+END_SRC

* Setting up brew environment

#+BEGIN_SRC sh
if [[ "$(uname)" == "Linux" ]]; then
  export BREW_PREFIX=/home/linuxbrew/.linuxbrew
elif [[ "$(arch)" == "i386" ]]; then
  export BREW_PREFIX=/usr/local;
else
  export BREW_PREFIX=/opt/homebrew;
fi

function add_bin {
  export PATH="$BREW_PREFIX/opt/$1/bin:$PATH"
}

function add_sbin {
  export PATH="$BREW_PREFIX/opt/$1/sbin:$PATH"
}

function add_dev_paths {
  export LDFLAGS="-L$BREW_PREFIX/opt/$1/lib $LDFLAGS"
  export CPPFLAGS="-I$BREW_PREFIX/opt/$1/include $CPPFLAGS"
}

function add_pkg_path {
  export PKG_CONFIG_PATH="$BREW_PREFIX/opt/$1/lib/pkgconfig:$PKG_CONFIG_PATH"
}

eval "$($BREW_PREFIX/bin/brew shellenv)"
#+END_SRC

* Setting up gem home

#+BEGIN_SRC sh
export GEM_HOME=$HOME/.gem
#+END_SRC

* Setting up PATH environment variable

#+BEGIN_SRC sh
if [[ "$(uname)" == "Linux" ]]; then
  export PATH="$HOME/.local/bin:$HOME/.npm-global/bin:$HOME/.cargo/bin:$PATH"
else
  export PATH="$GEM_HOME/bin:/Applications/kdiff3.app/Contents/MacOS/:$PATH"
  # gnubin
  export PATH="$BREW_PREFIX/opt/coreutils/libexec/gnubin:$PATH"
fi
#+END_SRC

#+RESULTS:

* Setting up installed libraries

#+BEGIN_SRC sh

if [[ "$(uname)" == "Linux" ]]; then
  # node@14
  add_bin node@14
  add_dev_paths node@14
fi

#+END_SRC

* Setting other paths
#+BEGIN_SRC sh
# local bin path
export PATH="$HOME/.local/bin:$PATH"

# doom bin path
export PATH="$HOME/.emacs.d/bin:$PATH"

# flutter bin path
export PATH="$HOME/development/flutter/bin:$PATH"

# cargo bin path
export PATH="$HOME/.cargo/bin:$PATH"

#+END_SRC

* Setting up oh-my-zsh environment variables

Set name of the theme to load --- if set to "random", it will
load a random theme each time oh-my-zsh is loaded, in which case,
to know which specific one was loaded, run: echo $RANDOM_THEME
See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#+BEGIN_SRC sh
ZSH_THEME="robbyrussell"
#+END_SRC

Set list of themes to pick from when loading at random
Setting this variable when ZSH_THEME=random will cause zsh to load
a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
If set to an empty array, this variable will have no effect.
#+BEGIN_SRC sh
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )
#+END_SRC

Uncomment the following line to use case-sensitive completion.
#+BEGIN_SRC sh
CASE_SENSITIVE="true"
#+END_SRC

Uncomment the following line to use hyphen-insensitive completion.
Case-sensitive completion must be off. _ and - will be interchangeable.
#+BEGIN_SRC sh
# HYPHEN_INSENSITIVE="true"
#+END_SRC

Uncomment the following line to disable bi-weekly auto-update checks.
#+BEGIN_SRC sh
# DISABLE_AUTO_UPDATE="true"
#+END_SRC

Uncomment the following line to automatically update without prompting.
#+BEGIN_SRC sh
# DISABLE_UPDATE_PROMPT="true"
#+END_SRC

Uncomment the following line to change how often to auto-update (in days).
#+BEGIN_SRC sh
# export UPDATE_ZSH_DAYS=13
#+END_SRC

Uncomment the following line if pasting URLs and other text is messed up.
#+BEGIN_SRC sh
# DISABLE_MAGIC_FUNCTIONS=true
#+END_SRC

Uncomment the following line to disable colors in ls.
#+BEGIN_SRC sh
# DISABLE_LS_COLORS="true"
#+END_SRC

Uncomment the following line to disable auto-setting terminal title.
#+BEGIN_SRC sh
# DISABLE_AUTO_TITLE="true"
#+END_SRC

Uncomment the following line to enable command auto-correction.
#+BEGIN_SRC sh
# ENABLE_CORRECTION="true"
#+END_SRC

Uncomment the following line to display red dots whilst waiting for completion.

#+BEGIN_SRC sh
# COMPLETION_WAITING_DOTS="true"
#+END_SRC

Uncomment the following line if you want to disable marking untracked files
under VCS as dirty. This makes repository status check for large repositories
much, much faster.
#+BEGIN_SRC sh
# DISABLE_UNTRACKED_FILES_DIRTY="true"
#+END_SRC

Uncomment the following line if you want to change the command execution time
stamp shown in the history command output.
You can set one of the optional three formats:
"mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
or set a custom format using the strftime function format specifications,
see 'man strftime' for details.
#+BEGIN_SRC sh
# HIST_STAMPS="mm/dd/yyyy"
#+END_SRC

Would you like to use another custom folder than $ZSH/custom?
#+BEGIN_SRC sh
# ZSH_CUSTOM=/path/to/new-custom-folder
#+END_SRC

* Plugins
Which plugins would you like to load?
Standard plugins can be found in ~/.oh-my-zsh/plugins/*
Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
Example format: plugins=(rails git textmate ruby lighthouse)
Add wisely, as too many plugins slow down shell startup.
#+BEGIN_SRC sh
plugins=(git
         zsh-navigation-tools
         zsh-interactive-cd
         vi-mode)
#+END_SRC

* Sourcing oh-my-zsh after all obligated staff
#+BEGIN_SRC sh
source $ZSH/oh-my-zsh.sh
#+END_SRC

* Preferred viewer and editor
Preferred editor for local and remote sessions.
Example:
#+BEGIN_SRC sh
#if [[ -n $SSH_CONNECTION ]]; then
#  export EDITOR='vim'
#else
#  export EDITOR='nvim'
#fi
#+END_SRC

#+BEGIN_SRC sh
export EDITOR='nvim'
export VIEWER='nvim'
#+END_SRC

* Aliases
Set personal aliases, overriding those provided by oh-my-zsh libs,
plugins, and themes. Aliases can be placed here, though oh-my-zsh
users are encouraged to define aliases within the ZSH_CUSTOM folder.
For a full list of active aliases, run `alias`.
#+BEGIN_SRC sh
alias zshconfig="$EDITOR ~/.zshrc"
alias ohmyzsh="$EDITOR ~/.oh-my-zsh"
alias vimconfig="$EDITOR ~/.vim/vimrc"

alias start_jupyter="jupyter notebook --ip='0.0.0.0' --NotebookApp.token='' --NotebookApp.password=''"

if [[ "$(uname)" == "Linux" ]]; then
  alias kittyconfig="$EDITOR ~/.config/kitty/kitty.conf"
  alias condarc="source ~/condarc"
  alias watch_gpu="watch -n0.5 'nvidia-settings -q GPUUtilization -q useddedicatedgpumemory'"
  alias watch_nvidia-smi="watch -n 0.5 nvidia-smi"
  alias docker_run="docker run -p 2222:22 \
      --runtime=nvidia \
      --mount type=bind,source=${HOME}/work,destination=/home/ubuntu \
      --privileged \
      --device /dev/video0 \
      -v /dev/snd:/dev/snd \
      -v /tmp/.X11-unix:/tmp/.X11-unix \
      -e DISPLAY=$DISPLAY \
      -e QT_X11_NO_MITSHM=1 \
      -e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native \
      -v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native \
      --hostname DOCKER_NVIDIA \
      -it tfbuild \
      /usr/bin/zsh"
  alias docker_build="docker build --build-arg UID=$(id -u) -t tfbuild ."
else
  alias condarc="source ~/miniforge3/bin/activate"
  alias subl="/Applications/Sublime\ Text.app/Contents/MacOS/sublime_text"
fi
#+END_SRC
